<style type="text/css">
.tname{
	font-size:18px;
	font-weight:bold;
	color:yellow;
	margin:10px;
}.members th{
	background-color:#fc5a1e;
	font-weight:bold;
}.members .cname{
	color:yellow;
	font-size:16px;
}.
</style>
<table border="0" width="100%" class="members" cellpadding="5">
	<tr>
		<th style='color:blue;'>Position</th>
		<th style='color:blue;'>Name</th>
		<th style='color:blue;'>About</th>
	</tr>
	<tr>
		<td colspan="3" style="border-bottom:1px dashed yellow;"><span style="color:orange; text-size:16px; font-weight:bold; text-align:center; margin-left:auto; margin-right:auto; display:block;">Tottenham Hotspur Lineup</span><b style="color:yellow;">Staff</b></td>
	</tr>
	<tr>
		<td valign="middle" align="center"><span style='color:yellow;'>Head Coach</span><br /><img src='/data/img/flags/shiny/48/Portugal.png' /></td>
		<td valign="middle" align="center"><span class='cname'>Andre Villas-Boas</span></td>
		<td valign="middle" width="50%;">
			<table border='0'>
				<tr>
					<td width="100px"><img src='http://www.tottenhamhotspur.com/media/images/team/2012-2013/andre-villas-boas.jpg' width='100px' height='100px'/></td>
					<td valign="top" style="padding:10px;"><div style="float:right; color:yellow; font-size:13px; clear:left;">
				Former Academica de Coimbra, Porto and Chelsea manager who was appointed as our new Head Coach in early July ahead of the 2012/2013 Season.
				</div></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td valign="middle" align="center"><span style='color:yellow;'>Assistant Head Coach</span><br /><img src='/data/img/flags/shiny/48/Germany.png' /></td>
		<td valign="middle" align="center"><span class='cname'>Steffen Freund</span></td>
		<td valign="middle" width="50%;">
			<table border='0'>
				<tr>
					<td width="100px"><img src='http://www.tottenhamhotspur.com/media/images/team/2012-2013/steffen-freund.jpg' width='100px' height='100px'/></td>
					<td valign="top" style="padding:10px;"><div style="float:right; color:yellow; font-size:13px; clear:left;">
				Appointed our Assistant Head Coach in July, 2012, nine years after his playing career with us came to an end. He became a real fans' favourite during his five-year spell at White Hart Lane as a player, signing for us on December 22, 1998.
				</div></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td valign="middle" align="center"><span style='color:yellow;'>First Team Coach</span><br /><img src='/data/img/flags/shiny/48/Portugal.png' /></td>
		<td valign="middle" align="center"><span class='cname'>Luis Martins</span></td>
		<td valign="middle" width="50%;">
			<table border='0'>
				<tr>
					<td width="100px"><img src='http://www.tottenhamhotspur.com/media/images/team/2012-2013/luis-martins.jpg' width='100px' height='100px'/></td>
					<td valign="top" style="padding:10px;"><div style="float:right; color:yellow; font-size:13px; clear:left;">
				Appointed to the role of First Team Coach having first embarked on a coaching career with hometown club Sporting Lisbon.
				</div></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td valign="middle" align="center"><span style='color:yellow;'>First Team Fitness Coach</span><br /><img src='/data/img/flags/shiny/48/Portugal.png' /></td>
		<td valign="middle" align="center"><span class='cname'>Jose Mario Rocha</span></td>
		<td valign="middle" width="50%;">
			<table border='0'>
				<tr>
					<td width="100px"><img src='http://www.tottenhamhotspur.com/media/images/team/2012-2013/jose-mario-rocha.jpg' width='100px' height='100px'/></td>
					<td valign="top" style="padding:10px;"><div style="float:right; color:yellow; font-size:13px; clear:left;">
				Arrived at White Hart Lane with Andre Villas-Boas, having worked alongside our new Head Coach throughout his management career so far.
				</div></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan="3" style="border-bottom:1px dashed yellow;"><b style="color:yellow;">Players</b></td>
	</tr>
	<tr>
		<td valign="middle" align="center"><span style='color:yellow;'>Goalkeeper</span><br /><img src='/data/img/flags/shiny/48/France.png' /></td>
		<td valign="middle" align="center"><span class='cname'>Hugo Lloris</span></td>
		<td valign="middle" width="50%;">
			<table border='0'>
				<tr>
					<td width="100px"><img class='img-circle' src='http://i.imm.io/XdMb.jpeg' width='100px' height='100px'/></td>
					<td valign="top" style="padding:10px;"><div style="float:right; color:yellow; font-size:13px; clear:left;">
				Arrived at White Hart Lane with Andre Villas-Boas, having worked alongside our new Head Coach throughout his management career so far.
				</div></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td valign="middle" align="center"><span style='color:yellow;'>Defender</span><br /><img src='/data/img/flags/shiny/48/France.png' /></td>
		<td valign="middle" align="center"><span class='cname'>Younes Kaboul</span></td>
		<td valign="middle" width="50%;">
			<table border='0'>
				<tr>
					<td width="100px"><img class='img-circle' src='http://i.imm.io/XdLJ.jpeg' width='100px' height='100px'/></td>
					<td valign="top" style="padding:10px;"><div style="float:right; color:yellow; font-size:13px; clear:left;">
				Arrived at White Hart Lane with Andre Villas-Boas, having worked alongside our new Head Coach throughout his management career so far.
				</div></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td valign="middle" align="center"><span style='color:yellow;'>Defender</span><br /><img src='/data/img/flags/shiny/48/Belgium.png' /></td>
		<td valign="middle" align="center"><span class='cname'>Jan Vertonghen</span></td>
		<td valign="middle" width="50%;">
			<table border='0'>
				<tr>
					<td width="100px"><img class='img-circle' src='http://i.imm.io/XdKX.jpeg' width='100px' height='100px'/></td>
					<td valign="top" style="padding:10px;"><div style="float:right; color:yellow; font-size:13px; clear:left;">
				Arrived at White Hart Lane with Andre Villas-Boas, having worked alongside our new Head Coach throughout his management career so far.
				</div></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td valign="middle" align="center"><span style='color:yellow;'>Defender</span><br /><img src='/data/img/flags/shiny/48/England.png' /></td>
		<td valign="middle" align="center"><span class='cname'>Michael Dawson</span></td>
		<td valign="middle" width="50%;">
			<table border='0'>
				<tr>
					<td width="100px"><img class='img-circle' src='http://i.imm.io/XdLg.jpeg' width='100px' height='100px'/></td>
					<td valign="top" style="padding:10px;"><div style="float:right; color:yellow; font-size:13px; clear:left;">
				Arrived at White Hart Lane with Andre Villas-Boas, having worked alongside our new Head Coach throughout his management career so far.
				</div></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td valign="middle" align="center"><span style='color:yellow;'>Defender</span><br /><img src='/data/img/flags/shiny/48/France.png' /></td>
		<td valign="middle" align="center"><span class='cname'>Benoit Assou-Ekotto</span></td>
		<td valign="middle" width="50%;">
			<table border='0'>
				<tr>
					<td width="100px"><img class='img-circle' src='http://i.imm.io/XdLP.jpeg' width='100px' height='100px'/></td>
					<td valign="top" style="padding:10px;"><div style="float:right; color:yellow; font-size:13px; clear:left;">
				Arrived at White Hart Lane with Andre Villas-Boas, having worked alongside our new Head Coach throughout his management career so far.
				</div></td>
				</tr>
			</table>
		</td>
	</tr>
</table>