<style type="text/css">
.tname{
	font-size:18px;
	font-weight:bold;
	color:yellow;
	margin:10px;
}.members th{
	background-color:#fc5a1e;
	font-weight:bold;
}.members .cname{
	color:yellow;
	font-size:16px;
}.
</style>
<table border="0" width="100%" class="members" cellpadding="5">
	<tr>
		<th style='color:blue;'>Name</th>
		<th style='color:blue;'>Role</th>
		<th style='color:blue;'>About</th>
	</tr>
	<tr>
		<td colspan="3" style="border-bottom:1px dashed yellow;"><b style="color:yellow;">Members</b></td>
	</tr>
	<tr>
		<td valign="middle" align="center" style="color:yellow;">David Gilmour</td>
		<td valign="middle" align="center" style="color:yellow;">Guitarist<br /><img class='img-circle' src='http://i.imm.io/XdXy.jpeg' width='100px' height='100px'/></td>
		<td valign="middle" width="50%;">
			<table border='0'>
				<tr>
					<!--<td width="100px"></td>-->
					<td valign="top" style="padding:10px;"><div style="float:right; color:yellow; font-size:13px; clear:left;">
				Arrived at White Hart Lane with Andre Villas-Boas, having worked alongside our new Head Coach throughout his management career so far.
				</div></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td valign="middle" align="center" style="color:yellow;">Roger Waters</td>
		<td valign="middle" align="center" style="color:yellow;">Singer<br /><img class='img-circle' src='http://i.imm.io/XdYq.jpeg' width='100px' height='100px'/></td>
		<td valign="middle" width="50%;">
			<table border='0'>
				<tr>
					<!--<td width="100px"><img class='img-circle' src='http://i.imm.io/XdYq.jpeg' width='100px' height='100px'/></td>-->
					<td valign="top" style="padding:10px;"><div style="float:right; color:yellow; font-size:13px; clear:left;">
				Arrived at White Hart Lane with Andre Villas-Boas, having worked alongside our new Head Coach throughout his management career so far.
				</div></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td valign="middle" align="center" style="color:yellow;">Richard Wright</td>
		<td valign="middle" align="center" style="color:yellow;">Pianist<br /><img class='img-circle' src='http://25.media.tumblr.com/tumblr_mafamujAvI1rghd8z_1347765656_cover.jpg' width='100px' height='100px'/></td>
		<td valign="middle" width="50%;">
			<table border='0'>
				<tr>
					<!--<td width="100px"><img class='img-circle' src='http://25.media.tumblr.com/tumblr_mafamujAvI1rghd8z_1347765656_cover.jpg' width='100px' height='100px'/></td>-->
					<td valign="top" style="padding:10px;"><div style="float:right; color:yellow; font-size:13px; clear:left;">
				Arrived at White Hart Lane with Andre Villas-Boas, having worked alongside our new Head Coach throughout his management career so far.
				</div></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td valign="middle" align="center" style="color:yellow;">Nick Mason</td>
		<td valign="middle" align="center" style="color:yellow;">Drummer<br /><img class='img-circle' src='http://i.imm.io/XdZq.jpeg' width='100px' height='100px'/></td>
		<td valign="middle" width="50%;">
			<table border='0'>
				<tr>
					<!--<td width="100px"><img class='img-circle' src='http://i.imm.io/XdZq.jpeg' width='100px' height='100px'/></td>-->
					<td valign="top" style="padding:10px;"><div style="float:right; color:yellow; font-size:13px; clear:left;">
				Arrived at White Hart Lane with Andre Villas-Boas, having worked alongside our new Head Coach throughout his management career so far.
				</div></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td valign="middle" align="center" style="color:yellow;">Syd Barrett</td>
		<td valign="middle" align="center" style="color:yellow;">Singer<br /><img class='img-circle' src='http://i.imm.io/XdZV.jpeg' width='100px' height='100px'/></td>
		<td valign="middle" width="50%;">
			<table border='0'>
				<tr>
					<!--<td width="100px"><img class='img-circle' src='http://i.imm.io/XdZV.jpeg' width='100px' height='100px'/></td>-->
					<td valign="top" style="padding:10px;"><div style="float:right; color:yellow; font-size:13px; clear:left;">
				Arrived at White Hart Lane with Andre Villas-Boas, having worked alongside our new Head Coach throughout his management career so far.
				</div></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan="3" style="border-bottom:1px dashed yellow;"><b style="color:yellow;">Press</b></td>
	</tr>
	<tr>
		<td colspan="3">
			<ul style="list-style:none;">
				<li><a href="http://www.pink-floyd.org/artint/revonthemove.htm">http://www.pink-floyd.org/artint/revonthemove.htm</a></li>
				<li><a href="http://www.pink-floyd.org/artint/117.htm">http://www.pink-floyd.org/artint/117.htm</a></li>
				<li><a href="http://www.pink-floyd.org/artint/118.htm">http://www.pink-floyd.org/artint/118.htm</a></li>
			</ul>
		</td>
	</tr>
</table>