<style type='text/css'>
.sched{

}.sched th{
	background-color:#fc5a1e;
	color:black;
	font-weight:bold;
	padding:5px;
}.sched td{

}.stats th{
	font-size:13px;
	color:white;
	background-color:red;
}.stats td{
	font-size:13px;
	color:black;
	background-color:white;
}.addEvent{
	background-color:#fc5a1e;
	padding:10px;
}
</style>
<div class='addEvent'>
	<center><button class='btn btn-primary' style='color:yellow;'>Add Event</span></center>
</div>
<table border='0' width='100%' class='sched' cellpadding='3'>
	<tr>
		<th align='left' style='border-bottom:1px dashed black;'>Date</th>
		<th align='left' style='border-bottom:1px dashed black;'>Event</th>
		<th align='left' style='border-bottom:1px dashed black;'>Type</th>
		<th align='left' style='border-bottom:1px dashed black;'>Directions</th>
	</tr>
	<tr>
		<td width='60px'>
			<table border='0' width='35px' class='stats' cellpadding='2'>
				<tr>
					<th>SUN</th>
				</tr>
				<tr>
					<td align='center'>24</td>
				</tr>
			</table>
			<span style='color:yellow; font-size:13px; float:right;'>5:30 - 7:00AM</span>
		</td>
		<td valign='middle'>LAKERS <b style='color:white; font-size:13px;'>vs</b> MAVERICKS</td>
		<td valign='middle'>Game</td>
		<td valign='middle'><a href='#' style='color:#fc5a1e;'>Get Directions</a></td>
	</tr>
	<tr>
		<td width='60px'>
			<table border='0' width='35px' class='stats' cellpadding='2'>
				<tr>
					<th>SUN</th>
				</tr>
				<tr>
					<td align='center'>25</td>
				</tr>
			</table>
			<span style='color:yellow; font-size:13px; float:right;'>5:30 - 8:00PM</span>
		</td>
		<td valign='middle'>LAKERS <b style='color:white; font-size:13px;'>vs</b> NUGGETS</td>
		<td valign='middle'>Tournament</td>
		<td valign='middle'><a href='#' style='color:#fc5a1e;'>Get Directions</a></td>
	</tr>
	<tr>
		<td width='60px'>
			<table border='0' width='35px' class='stats' cellpadding='2'>
				<tr>
					<th>SUN</th>
				</tr>
				<tr>
					<td align='center'>28</td>
				</tr>
			</table>
			<span style='color:yellow; font-size:13px; float:right;'>7:00 - 9:00PM</span>
		</td>
		<td valign='middle'>TIMBERWOLVES <b style='color:white; font-size:13px;'>vs</b> LAKERS</td>
		<td valign='middle'>Practice</td>
		<td valign='middle'><a href='#' style='color:#fc5a1e;'>Get Directions</a></td>
	</tr>
</table>