<style type='text/css'>
.sched .header{
	font-size:16px;
	color:yellow;
	font-weight:bold;
	/*padding:10px;
	background-color:yellow;*/
}.sched .sched-list{

}.sched .sched-list .head-min th{
	color:black;
	background-color:#fc5a1e;
}.sched .res-list td{
	color:white;
}

.sched .res-list .head-min th{
	color:black;
	background-color:#fc5a1e;
}.sched .res-list td{
	color:white;
}.stats th{
	font-size:13px;
	color:white;
	background-color:red;
}.sched .res-list .stats td{
	font-size:13px;
	color:black;
	background-color:white;
}.sched .sched-list .stats td{
	font-size:13px;
	color:black;
	background-color:white;
}.score td{
	color:blue;
}
</style>
<table border='0' width='100%' style='background-color:#fc5a1e; border-bottom:1px dashed black; margin-bottom:10px;' class='score'>
	<tr>
		<th style='color:blue;'>Wins</th>
		<th style='color:blue;'>Losses</th>
		<th style='color:blue;'>Ties</th>
	</tr>
	<tr>
		<td align='center'>12</td>
		<td align='center'>1</td>
		<td align='center'>0</td>
	</tr>
</table>
<div class='sched'>
	<div class='header'>
		Schedule
	</div>
	<table border='0' class='sched-list' width='100%'>
		<tr class='head-min'>
			<th style='border-bottom:1px dashed black; color:blue;' align='middle'>Date</th>
			<th style='border-bottom:1px dashed black; color:blue;' align='left'>Event</th>
			<th style='border-bottom:1px dashed black; color:blue;' align='left'>Type</th>
			<th style='border-bottom:1px dashed black; color:blue;' align='left'>Directions</th>
		</tr>
		<tr>
			<td width='50px' align='center'>
				<table border='0' width='40px' class='stats' cellpadding='2'>
					<tr>
						<th>SAT</th>
					</tr>
					<tr>
						<td align='center'>23</td>
					</tr>
				</table>
			</td>
			<td>
			Celtics <span style='color:white; font-size:13px; font-weight:bold;'>vs</span> Lakers
			</td>
			<td>Game</td>
			<td><a href='#'>Get Directions</a></td>
		</tr>
	</table>
	<div class='header' style='margin-top:15px;'>
		Results
	</div>
	<table border='0' class='res-list' width='100%'>
		<tr class='head-min'>
			<th style='border-bottom:1px dashed black; color:blue;' align='center'>Date</th>
			<th style='border-bottom:1px dashed black; color:blue;' align='center'>Event</th>
		</tr>
		<tr>
			<td width='50px' align='center'>
				<table border='0' width='40px' class='stats' cellpadding='2'>
					<tr>
						<th>THU</th>
					</tr>
					<tr>
						<td align='center'>14</td>
					</tr>
				</table>
			</td>
			<td align='center' valign='middle'>
				<table border='0' width='100%'>
					<tr>
						<th align="right" style="color:#FCDC3B;"><i class='icon-home icon-white'></i> Lakers</th>
						<th></th>
						<th align="left" style="color:#FCDC3B;">Clippers</th>
					</tr>
					<tr>
						<td align="right">101</td>
						<td align="middle">-</td>
						<td align="left"><b>125</b></td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
</div>