<style type='text/css'>
.rsong{

}.rsong th{
	color:yellow;
	font-size:13px;
	font-weight:bold;
}.rsong td{
	font-size:13px;
}.rsong td.sname{
	color:yellow;
}.album-name{
	color:yellow;
	font-size:15px;
	font-weight:bold;
}.stats{
	border-bottom:1px dashed black;
	background-color:#fc5a1e;
}.stats td{
	color:blue;
	font-size:15px;
}.stats .prompt{
	color:blue;
	font-size:15px;
}
</style>
<div class="stats">
	<table border='0' width='100%' style="margin-bottom:10px;">
		<tr>
			<td colspan='2' style='height:10px;'></td>
		</tr>
		<tr>
			<td class='prompt' align='center' width='50%' style="border-right:1px dashed black; padding-right:10px;">Plays <i class='icon-play'></i><span style='color:blue;'> 5,670,234,234,354,234</span></td>
			<td class='prompt' align='center' width='50%'>Downloads <i class='icon-download-alt'></i><span style='color:blue;'> 34,235,234</span></td>
		</tr>
	</table>
</div>
<table border='0' style='margin:10px;' width='100%'>
	<tr>
		<td valign='top' width='60px'><img src='https://i1.sndcdn.com/artworks-000040115876-ietlpt-t120x120.jpg?6c55c25' class='img-rounded' width='55px'/></td>
		<td>
			<span class='album-name'>Sick Mixes</span>
			<table border='0' class='rsong' width='100%;' cellpadding='5'>
				<tr>
					<th></th>
					<th align='left'>Title</th>
					<th align='left'>Album</th>
					<th align='left'>Duration</th>
				</tr>
				<tr>
					<td width='25px;'><button class="btn btn-mini btn-warning" style="color:black;">PLAY</button></td>
					<td class='sname'>house</td>
					<td class='duration'>Sick Mixes</td>
					<td class='duration'>0:16</td>
				</tr>
				<tr>
					<td width='25px;'><button class="btn btn-mini btn-warning" style="color:black;">PLAY</button></td>
					<td class='sname'>song 2</td>
					<td class='duration'>Sick Mixes</td>
					<td class='duration'>0:16</td>
				</tr>
				<tr>
					<td width='25px;'><button class="btn btn-mini btn-warning" style="color:black;">PLAY</button></td>
					<td class='sname'>song 3</td>
					<td class='duration'>Sick Mixes</td>
					<td class='duration'>0:08</td>
				</tr>
				<tr>
					<td width='25px;'><button class="btn btn-mini btn-warning" style="color:black;">PLAY</button></td>
					<td class='sname'>song 5</td>
					<td class='duration'>Sick Mixes</td>
					<td class='duration'>0:16</td>
				</tr>
				<tr>
					<td width='25px;'><button class="btn btn-mini btn-warning" style="color:black;">PLAY</button></td>
					<td class='sname'>song 6</td>
					<td class='duration'>Sick Mixes</td>
					<td class='duration'>0:45</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td style='height:20px; border-bottom:1px dashed yellow;'></td>
	</tr>
	<tr>
		<td valign='top' width='60px'><img src='https://i1.sndcdn.com/artworks-000040066249-yqjh25-t120x120.jpg?6c55c25' class='img-rounded' width='55px'/></td>
		<td>
			<span class='album-name'>Easy Listening</span>
			<table border='0' class='rsong' width='100%;' cellpadding='5'>
				<tr>
					<th></th>
					<th align='left'>Title</th>
					<th align='left'>Album</th>
					<th align='left'>Duration</th>
				</tr>
				<tr>
					<td width='25px;'><button class="btn btn-mini btn-warning" style="color:black;">PLAY</button></td>
					<td class='sname'>house</td>
					<td class='duration'>Sick Mixes</td>
					<td class='duration'>0:16</td>
				</tr>
			</table>
		</td>
	</tr>
</table>