<style type="text/css">
.signup-grad{
	background-image: linear-gradient(right bottom, #FCDC3B 15%, #FFEC8B 41%, #FFFFFF 82%);
	background-image: -o-linear-gradient(right bottom, #FCDC3B 15%, #FFEC8B 41%, #FFFFFF 82%);
	background-image: -moz-linear-gradient(right bottom, #FCDC3B 15%, #FFEC8B 41%, #FFFFFF 82%);
	background-image: -webkit-linear-gradient(right bottom, #FCDC3B 15%, #FFEC8B 41%, #FFFFFF 82%);
	background-image: -ms-linear-gradient(right bottom, #FCDC3B 15%, #FFEC8B 41%, #FFFFFF 82%);

	background-image: -webkit-gradient(
		linear,
		right bottom,
		left top,
		color-stop(0.15, #FCDC3B),
		color-stop(0.41, #FFEC8B),
		color-stop(0.82, #FFFFFF)
	)
}.signup{
	background-color:rgba(255,255,255,.8);
	margin-top:-25px;
	margin-bottom:-10px;
	padding:0px;
}.favsul li{
	color:black;
}.coming-soon{
	font-size:20px;
	color:yellow;
	position:absolute;
	margin-left:80px;
	margin-top:8px;
	background-color:rgba(255,255,255,.3);
	padding:5px;
	width:400px;
	-moz-border-radius:5px;
	-webkit-border-radius:5px;
	border-radius:5px;
}
</style>
<div class="terms">
	<a href="#" style="color:white;">Privacy</a> &middot; <a href="#" style="color:white;">Contact</a> &middot; <a href="#" style="color:white;">Terms</a> &middot; <a href="#" style="color:white;">Cookies</a></span>
</div>
<table border="0" width="100%;">
	<tr>
		<td align="left">
			<table border="0" width="100%;" >
				<tr>
					<td align="left">
						<img src="http://i.imm.io/19S6Z.png" style="width:340px; margin-left:70px; margin-bottom:15px; /*background-image:url('http://25.media.tumblr.com/6d22e7bad499565c7625c06c45ab731f/tumblr_mk57x4eRSI1s65areo1_400.gif'); -moz-box-shadow:0 2px 20px -5px #444; -webkit-box-shadow:0 2px 20px -5px #444; box-shadow:0 2px 20px -5px #444;*/" /><!-- http://i.imm.io/10Nfk.png /data/img/header_upper_left.png -->
					</td>
					<td align="right">
						<form>
						<table border="0" style="margin-top:10px; margin-right:10px;">
							<tr>
								<td><input style="height:30px; width:190px;" type="text" id="emailSignin" placeholder="Email" /></td>
								<td><input style="height:30px; width:190px;" type="password" id="passwordSignin" placeholder="Password" /></td>
							</tr>
							<tr>
								<td><label><input type="checkbox" style="position:relative; bottom:3px;" onclick="alert('Ha ha in your dreams.');"/><span style="font-size:13px; margin-left:3px;">Remember Me</span></label></td>
								<td>
									<a style="font-size:13px; position:relative; bottom:3px; right:3px;" href="?p=forgot_password">Forgot Password?</a>
									<button class="btn btncustom" onclick="signIn();" style="margin-top:-5px;"><span style="color:blue;">Sign In</span></button>
								</td>
							</tr>
						</table>
						</form>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td align="center" style="padding-top:5px;">
			<table border="0" cellpadding="0" style="margin-top:10px;">
				<tr>
					<td style="padding-top:5px; color:black;">
						<!-- Pwf0 PwFj PwHx PwI0 PwIo PwIA PwKy PwLd PwLq http://i46.tinypic.com/10ofsbl.png http://i50.tinypic.com/v7d40i.gif SMDt SMEP SMFh SMEP SMFQ-->
						<!--<h1 style="text-align:center; font-size:45px;"><b style="color:#fc5a1e;">Welcome.</b></h1>-->
						<!-- LOGO OLD POSITION <img src="http://i.imm.io/10Nfk.png" width="397px;" height="88px;" style="margin-left:55px; position:relative; bottom:60px;"/><br /> -->
						<!-- ffde0f -->
						<!--<span style="color:white; font-size:20px; position:relative; bottom:10px; right:10px;"><i class='icon-film icon-white' onmouseover="switchAct(6);" style='position:relative; right:10px; top:90px;'></i><b>The new social network for <span style="color:yellow;">Music</span> and <span style="color:yellow;">Sports</span> fans.</b></span>-->
						<form class="form-horizontal" id="act-form" style="width:500px;" method="POST">
			  <div class='act-icon-holder'>
			  <img src="http://i50.tinypic.com/2lic02p.gif" style="float:right; margin-top:15px; margin-right:15px; display:none;" class="ban-icon" width="50px" height="50px"/>
			  <img src="http://i47.tinypic.com/2cqifj7.png" style="float:right; margin-top:15px; margin-right:15px; display:none;" class="mus-icon" width="40px" height="40px"/>
			  <img src="http://i.imm.io/W2yT.png" style="float:right; margin-top:15px; margin-right:15px; display:none;"  class="tea-icon" width="40px" height="40px"/>
			  <img src="http://i49.tinypic.com/30bh02h.png" style="float:right; margin-top:15px; margin-right:15px;" class="gen-icon" width="40px" height="40px"/>
			  <img src="http://i.imm.io/W2Cn.png" style="float:right; margin-top:15px; margin-right:15px; display:none;" class="ath-icon" width="50px" height="50px"/>
			  <img src="http://i50.tinypic.com/1pbdzr.gif" style="float:right; margin-top:15px; margin-right:15px; display:none;" class="age-icon" width="50px" height="50px"/>
			  </div>
			 <script>
			 var sports = ["Aquatics",
						"Archery",
						"Automobile Racing",
						"Badminton",
						"Base Jumping",
						"Baseball",
						"Basketball",
						"Beach Volleyball",
						"Biathlon",
						"Bobsleigh",
						"Body Building",
						"Bowling",
						"Boxing",
						"Camping",
						"Canoeing",
						"Cheerleading",
						"Chess",
						"Classical Dance",
						"Cricket",
						"Cross Country Running",
						"Cross Country Skiing",
						"Curling",
						"Cycling",
						"Darts",
						"Decathlon",
						"Diving",
						"Dog Training",
						"Down Hill Skiing",
						"Equestrianism",
						"Fencing",
						"Figure Skating",
						"Fishing",
						"Flag Football",
						"Football",
						"Golf",
						"Gymnastics",
						"Hang Gliding",
						"High Jump",
						"Hiking",
						"Hockey",
						"Hunting",
						"Ice Skating",
						"Inline Skating",
						"Judo",
						"Karate",
						"Kayaking",
						"Lacrosse",
						"Land Sailing",
						"Long Jump",
						"Luge",
						"Modern Dance",
						"Modern Pentathlon",
						"Motorcycle Racing",
						"Mountain Biking",
						"Mountaineering",
						"Netball",
						"Paint Ball",
						"Para Gliding",
						"Parachuting",
						"Pool Playing",
						"Quad Biking",
						"Racquetball",
						"River Rafting",
						"Rock Climbing",
						"Rodeo Riding",
						"Roller Skating",
						"Rowing",
						"Rugby",
						"Sailing",
						"Scuba Diving",
						"Shooting",
						"Shot Put",
						"Shuffleboard",
						"Skateboarding",
						"Skeet Shooting",
						"Snow Biking",
						"Snow Boarding",
						"Snow Sledding",
						"Soccer",
						"Speed Skating",
						"Sport Fishing",
						"Sprint Running",
						"Squash",
						"Stunt Plane Flying",
						"Sumo Wrestling",
						"Surfing",
						"Swimming",
						"Synchronized Swimming",
						"Table Tennis",
						"Taekwondo",
						"Tennis",
						"Track and Field",
						"Triathlon",
						"Volleyball",
						"Water Polo",
						"Water Skiing",
						"Weight Lifting",
						"Wheelchair Basketball",
						"White Water Rafting",
						"Wind Surfing",
						"Wrestling",
						"Yachting",
						"Yoga"];

			 var musics = ["Alternative",
						"Blues",
						"Children's Music",
						"Christian & Gospel",
						"Classic Hits",
						"Classical",
						"Comedy",
						"Country",
						"Dance",
						"Electronic",
						"Fitness & Workout",
						"Hip-Hop/Rap",
						"Jazz",
						"Latino",
						"Live Music",
						"Metal",
						"Pop",
						"R&B/Soul",
						"Reggae",
						"Rock",
						"Singer/Songwriter",
						"Soundtrack",
						"World"];
			 function dispVideo(){
				$(".cont-video").hide();
				$(".spuzik-video").show();
			 }

			 function start(){
				$(".act-icon-holder").hide();
				$(".signup .second").hide();
				$(".signup .third").hide();
				$(".signup .first").html("<span class='label label-info' style='color:yellow; background-color:#0069cc;'>Step 1</span> <!--<b style='color:black;'><center>Select an account from above to sign up.</b>--></center>\
				<img onclick='dispVideo();' class='cont-video' src='http://i.imm.io/15uhO.png' style='width:100%; margin-top:10px; cursor:pointer;'/>\
				<object width='640' height='360' class='spuzik-video' style='display:none;'>\
				  <param name='movie' value='https://www.youtube.com/v/2ryYDvE6UKg?controls=0&showinfo=0&version=3&autoplay=1'></param>\
				  <param name='allowFullScreen' value='true'></param>\
				  <param name='allowScriptAccess' value='always'></param>\
				  <embed src='https://www.youtube.com/v/2ryYDvE6UKg?controls=0&showinfo=0&version=3&autoplay=1' type='application/x-shockwave-flash' allowfullscreen='true' allowScriptAccess='always' width='480' height='280'></embed>\
				</object>\
				").show();
			 }

			 $(document).ready(function(){
				start();
				switchAct(0);
			 });

			 function favs(){
				$(".act-icon-holder").hide();
				$(".signup .second").hide();
				$(".signup .third").hide();
				var sport = "";
				for(var i = 0;i < sports.length;i++){
					sport += "<li><label><input type='checkbox' style='position:relative; bottom:3px; right:2px;' />"+sports[i]+"</label></li>";
				}
				var music = "";
				for(var i = 0;i < musics.length;i++){
					music += "<li><label>"+musics[i]+"<input type='checkbox' style='position:relative; bottom:3px; left:2px;' /></label></li>";
				}
				$(".signup .first").html("<span class='label label-success' style='color:yellow; background-color:#0000d9;'>Step 3</span><b style='color:black;'><center>Compatibility Check.</b><br /><span style='font-size:13px;'>This information will be used for recommendations.</span></center>\
				<table border='0' width='100%;'>\
					<tr>\
						<th align='left' style='color:#156ed4;'>Sports</th>\
						<th align='right' style='color:#156ed4;'>Genres</th>\
					</tr>\
					<tr>\
						<td width='50%;' valign='top' align='left'>\
							<ul class='favsul sport-ul' style='list-style:none; margin-left:3px;'>"+sport+"</ul>\
						</td>\
						<td width='50%;' valign='top' align='right'>\
							<ul class='favsul music-ul' style='list-style:none;'>"+music+"</ul>\
						</td>\
					</tr>\
				</table>\
				").show();
			 }

			 $(".u0").tooltip('toggle');
			 $(".u0").tooltip('hide');
			 </script>
			  <div class='first'></div>
			  <div class='second'>
			  <!--<h4 id="act-display-type" style="color:black;">Standard</h4>-->
			  <div class="alert alert-info loading-act" style="display:none;">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<img src="/data/img/loader.gif" /> <b>Loading...</b> We're verifying that your information is valid.
			  </div>
			<script>
								$(document).ready(function(){
									$(".month").change(function(){
											if(jQuery.inArray(parseInt($(".month").val()),[9,4,6,11]) != -1){ //has 30 days
													displayDays(30);
											}else if(jQuery.inArray(parseInt($(".month").val()),[1,3,5,7,8,10,12]) != -1){ //has 31 days
													displayDays(31);
											}else{ //has 28 days
													displayDays(29);
											}
									});

									$(".ind-act").hover(function(){
											$(this).find(".arrow").show();
									},function(){
											$(this).find(".arrow").hide();
									});
								});

								function displayDays(amt){
										var s = "";
										for(var i = 1;i <= amt;i++){
												s+="<option>"+String(i)+"</option>";
										}
										$(".days").html(s);
								}
								//$(".act-tooltop").popover('hide');

								$(".act-tooltip").popover('show');
								$(".expand-act-button").click(function(){
										$(".expand-act").slideDown(300);
								});

								function switchAct(act){
									$(".act-icon-holder").hide();
									$(".second").show();
									$(".first").hide();
									$(".third").hide();
									switch(act){
											case 0: //general
											case 1: //athelete
											case 3: //musician
											case 5: //agent
													$("#fnamed").show();
													$("#lnamed").show();
													$("#dobd").show();
													$("#anamed").hide();
													switch(act){
														case 0:
															$(".gen-icon").show();
															$(".ath-icon").hide();
															$(".tea-icon").hide();
															$(".ban-icon").hide();
															$(".mus-icon").hide();
															$(".age-icon").hide();
															break;
														case 1:
															$(".ath-icon").show();
															$(".tea-icon").hide();
															$(".ban-icon").hide();
															$(".mus-icon").hide();
															$(".gen-icon").hide();
															$(".age-icon").hide();
															break;
														case 3:
															$(".mus-icon").show();
															$(".gen-icon").hide();
															$(".ath-icon").hide();
															$(".tea-icon").hide();
															$(".ban-icon").hide();
															$(".age-icon").hide();
															break;
														case 5:
															$(".mus-icon").hide();
															$(".gen-icon").hide();
															$(".ath-icon").hide();
															$(".tea-icon").hide();
															$(".ban-icon").hide();
															$(".age-icon").show();
															break;
													}
												break;
											case 2: //team
												$(".tea-icon").show();
												$(".mus-icon").hide();
												$(".gen-icon").hide();
												$(".ath-icon").hide();
												$(".ban-icon").hide();
												$(".age-icon").hide();
												break;
											case 4: //band
												$("#anamed").show();
												$("#fnamed").hide();
												$("#lnamed").hide();
												$("#dobd").hide();
												$(".tea-icon").hide();
												$(".mus-icon").hide();
												$(".gen-icon").hide();
												$(".ath-icon").hide();
												$(".ban-icon").show();
												$(".age-icon").hide();
												break;
											case 6: //show start menu
												start();
												break;
												switch(act){
													case 2:
														$(".tea-icon").show();
														$(".mus-icon").hide();
														$(".gen-icon").hide();
														$(".ath-icon").hide();
														$(".ban-icon").hide();
														$(".age-icon").hide();
														break;
													case 4:
														$(".tea-icon").hide();
														$(".mus-icon").hide();
														$(".gen-icon").hide();
														$(".ath-icon").hide();
														$(".ban-icon").show();
														$(".age-icon").hide();
														break;
												}
												break;
										}
										var type = ['Standard','Athlete','Team','Musician','Band','Agent'];
										$("#act-display-type").html(type[act]);
										$("#type").attr("value",act);
								}

								function signIn(){
									$.ajaxSetup({async:false});
									var actionUrl = "actions.php?type=signIn";
									$.post(
										actionUrl,
										{
											email: $("#emailSignin").val(),
											password: $("#passwordSignin").val()
										},
										function(data,status){
											var parseJSON = $.parseJSON(data);
											if(parseJSON.status == "error"){
												window.location.replace("/?p=signin&s=1")
											}else{
												//window.location.replace("/?p=notifications")
												window.location.replace("/?p=profile")
											}
										}
									);
								}

								function signUp(){
									$.ajaxSetup({async:false});
									var actionUrl = "actions.php?type=addUser";

									$.post(
											actionUrl,
											{
												fname: 		$("#fname").val(),
												lname:  	$("#lname").val(),
												email: 		$("#email").val(),
												password: 	$("#password").val(),
												passwordv: 	$("#passwordv").val(),
												month: 		$("#month").val(),
												day: 		$("#day").val(),
												year: 		$("#year").val(),
												type: 		0
											},
											function(data,status){
												var parseJSON = $.parseJSON(data);
												if(parseJSON.status_type == "internal"){
													alert(parseJSON.status_msg);
													$(".signup-error").html("There was a database issue.");
													$(".signup-error").show();
												}

												if(parseJSON.status == "error"){
														var error = new Array();
														if(typeof parseJSON.status_itr.fname != "undefined"){
																$("#fname").parent().parent().addClass("error");
																error.push(parseJSON.status_itr.fname);
														}else{
																$("#fname").parent().parent().removeClass("error");
														}

														if(typeof parseJSON.status_itr.lname != "undefined"){
																$("#lname").parent().parent().addClass("error");
																error.push(parseJSON.status_itr.lname);
														}else{
																$("#lname").parent().parent().removeClass("error");
														}
														if(typeof parseJSON.status_itr.email != "undefined"){
																$("#email").parent().parent().parent().addClass("error");
																error.push(parseJSON.status_itr.email);
														}else{
																$("#email").parent().parent().parent().removeClass("error");
														}
														if(typeof parseJSON.status_itr.password != "undefined"){
																$("#password").parent().parent().addClass("error");
																$("#passwordv").parent().parent().addClass("error");
																error.push(parseJSON.status_itr.password);
														}else{
																$("#password").parent().parent().removeClass("error");
																$("#passwordv").parent().parent().removeClass("error");
														}

														if(typeof parseJSON.status_itr.dob != "undefined"){
																$("#dob").parent().parent().addClass("error");
																error.push(parseJSON.status_itr.dob);
														}else{
																$("#dob").parent().parent().removeClass("error");
														}
														//alert(error.length);
														$(".signup-error-b").html(error.length.toString());
														var alertText = "";
														for(var i = 0;i < error.length;i++){
																alertText+="<li style='color:#333; font-size:14px;'>"+error[i]+"</li>";
														}
														$(".signup-error-ul").html(alertText);
														$(".signup-error").show();
												}else{
														$(".signup-error").hide();
														$("#act-display-type").hide();
														$(".signup-success-email").html($("#email").val());
														$(".signup-success2").show();
														$(".form-main").hide();
												}
										}
									).fail(function(){ alert("didnt go through"); });
									//$.ajaxSetup({async:true});
								}

								function hideIt(){
										$(".form-control").slideToggle("slow",function(){
												$(".loading-act").show();
										});
								}
							  </script>
								</div>
							</form>
						</div>
					</td>
				</tr>

				<tr>
					<td>
						<style type="text/css">
						.signup-error{
							background-color:#ff9d9d;
							border-bottom:2px solid #b94a48;
							padding:10px;
							-moz-border-radius:5px;
							-webkit-border-radius:5px;
							border-radius:5px;
							margin:5px 5px 15px 5px;
						}.signup-error .text{
							color:#333;
							font-size:15px;
						}.control-label{
							color:black;
						}
						.success-label{
							background-color:#c8e5bc;
							border-bottom:2px solid #4a8332;
							padding:10px;
							-moz-border-radius:5px;
							-webkit-border-radius:5px;
							border-radius:5px;
							margin:5px 5px 15px 5px;
						}.success-label .text{
							color:#333;
							font-size:15px;
						}
						</style>
						<div class="signup">
						<!--<div class="error-warning">
							<span class="text"><img src="http://i41.tinypic.com/f9eez8.png" width="20px;" height="20px;" style="position:relative; bottom:1px;"/>Please correct the errors below.</span>
						</div>-->
						<div style="width:100%; background-image:url('http://i43.tinypic.com/juydg9.png'); -moz-border-top-left-radius:5px; -webkit-border-top-left-radius:5px; border-top-left-radius:5px; -moz-border-top-right-radius:5px; -webkit-border-top-right-radius:5px; border-top-right-radius:5px;">
							<div style="padding:10px 5px 25px 5px;">
								<table border="0" width="100%;" height="100%;" style="margin-top:15px;">
									<tr>
										<td width="170px;" valign="middle" align="center"><span style="font-weight:bold; margin:6px; font-size:28px;">Sign Up</span></td>
										<td><span style="color:white; font-size:20px; font-family: 'Roboto Condensed', cursive;">Create your identity in the world of<br /><b style="color:yellow;">music</b> and <b style="color:yellow;">sports</b>!</td>
									</tr>
								</table>
							</div>
						</div>
						<div class="form-horizontal" style="padding:15px 5px 5px 5px;">
							<div class="signup-error" style="display:none;">
								<img src="http://i41.tinypic.com/f9eez8.png" width="20px;" height="20px;" style="position:relative; bottom:1px;"/>
								<span style="color:#333; font-size:14px;">There were <b class="signup-error-b" style="color:#333">2</b> errors while trying to create your account.</span><br />
								<ul class="signup-error-ul" style="color:rgb(185,74,72);"></ul>
							</div>
							<div class="signup-success2 success-label" style="display:none;">
								<img src="http://i44.tinypic.com/125gkg9.gif" width="16px;" height="16px;" style="position:relative; bottom:1px; right:3px;"/><span style="color:#333; font-size:14px;">A confirmation email has been sent to <b class="signup-success-email" style="color:#333;"></b>.<br />Please click on the verification link contained within the email.</span>
							</div>
							<div class="form-main">
								<div id="first_name" class="control-group">
									<label class="control-label" for="fname" style="color:black;">First name</label>
									<div class="controls">
									  <input style="height:30px;" type="text" id="fname" placeholder="First name">
									</div>
								</div>
								<div id="last_name" class="control-group">
									<label class="control-label" for="fname" style="color:black;">Last name</label>
									<div class="controls">
										<input style="height:30px;" type="text" id="lname" placeholder="Last name">
									</div>
								</div>
								<div class="control-group">
									<label class="control-label" for="inputEmail" style="color:black;">Email</label>
									<div class="controls">
										<div class="input-prepend">
											<span class="add-on"><i class="icon-envelope"></i></span>
											<input style="height:30px; width:220px;" class="span2" type="text" id="email" placeholder="Email">
										</div>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label" for="password" style="color:black;">Password</label>
									<div class="controls">
										<input style="height:30px;" type="password" id="password" placeholder="Password">
									</div>
								</div>
								<div class="control-group">
									<label class="control-label" for="passwordv" style="color:black;">Verify password</label>
									<div class="controls">
										<input style="height:30px;" type="password" id="passwordv" placeholder="Verify password">
									</div>
								</div>
								<div id="dobd" class="control-group">
									<label class="control-label" for="dob" style="color:black;">Date of birth</label>
									<div class="controls">
										<select class="month" id="month" style="width:80px;">
											<option value="1">Jan</option>
											<option value="2">Feb</option>
											<option value="3">Mar</option>
											<option value="4">Apr</option>
											<option value="5">May</option>
											<option value="6">Jun</option>
											<option value="7">Jul</option>
											<option value="8">Aug</option>
											<option value="9">Sep</option>
											<option value="10">Oct</option>
											<option value="11">Nov</option>
											<option value="12">Dec</option>
										</select>
										<select class="days" id="day" style="width:60px;">
										<?php
											foreach(range(1,31) as $i){
												echo "<option value=\"".$i."\">".$i."</option>";
											}
										?>
										</select>
										<select style="width:90px;" id="year">
										<?php
											$goto = date('Y')-13; //users must be 13 and older
											foreach(range($goto,($goto-100)) as $year){
												echo "<option value=\"".$year."\">".$year."</option>";
											}
										?>
										</select>
									</div>
								</div>
								<div class="control-group">
									<div class="controls">
									<span style="font-size:14px; color:black;">By clicking the &quot;Next&quot; button you agree<br /> to the <a style="color:blue;" href="/?p=tos">Terms of Service</a></span>
									</div>
								</div>
								<div class="control-group">
									<div class="controls">
										<button type="button" onclick="signUp();" name="submit" class="btn btncustom signup-btn" style='color:blue;'>Next</button>
									</div>
								</div>
							</div>
						</div>
					</td>
				</tr>
				<tr>
					<td align="right" style="background-image:url('http://i43.tinypic.com/juydg9.png'); border-bottom-right-radius:5px; -moz-border-bottom-right-radius:5px; -webkit-border-bottom-right-radius:5px; border-bottom-left-radius:5px; -moz-border-bottom-left-radius:5px; -webkit-border-bottom-left-radius:5px;">
						<div style="text-align:center; padding:0px; margin-top:10px; margin-bottom:10px;">
							<i style="color:black; font-family:'Roboto Condensed'; font-size:20px; color:white;">Where fans can <span style="color:yellow;">vent</span> about the things that really matter.</i>
						</div>
					</td>
					<td></td>
				</tr>
			</table>
		</td>
	</tr>
</table>