<script>
$(document).ready(function(){
	$("#items").accordion({
		heightStyle: "content"
	});
});
</script>
<style type="text/css">
#items{
	padding:10px;
	height:100%;
}#items h3{
	color:white;
	cursor:pointer;
}#items p{
	color:black;
}#items .round-y{
	background-color:yellow;
	-moz-border-radius:5px;
	-webkit-border-radius:5px;
	border-radius:5px;
	border:0px solid black;
	padding:10px;
}.unite-post .unite-link{
	background-color:yellow;
	-moz-border-radius:5px;
	-webkit-border-radius:5px;
	border-radius:5px;
	border:0px solid #000;
	padding:10px;
}
</style>
<div class="site-content">
	<table border="0" width="100%;" height="100%" cellspacing="0" cellpadding="0">
		<tr>
			<td colspan="2" height="65px;"></td>
		</tr>
		<tr>
			<td width="30%" valign="top">
				<div style="background-color:#179bff; padding:10px; height:100%;">
					<table border="0" style="float:right;">
						<tr>
							<td align="right"><img src="http://i.imm.io/1akBD.png" width="30px;" height="30px;" style="margin:5px; margin-bottom:7px;"/></td>
							<td align="center">
								<button class="btn btncustomwhite" style="background-color:white;"><span style="color:blue; font-weight:bold;">Unite</span></button>
							</td>
							<td align="left"><img src="http://i.imm.io/1akFm.png" width="30px;" height="30px;" style="margin:5px; margin-bottom:7px;"/></td>
						</tr>
					</table>
					<div id="items">
						<h3>Photos</h3>
						<div class="round-y">
							<img src="http://54.243.129.126/usr_content/pics/50ff4334ca885_t.jpg" width="80px;" height="80px;" style="margin-top:3px;"/>
							<img src="http://54.243.129.126/usr_content/pics/50ff4359c6ec3_t.jpg" width="80px;" height="80px;" style="margin-top:3px;"/>
							<img src="http://54.243.129.126/usr_content/pics/50ff45a163bc2_t.jpg" width="80px;" height="80px;" style="margin-top:3px;"/>
							<img src="http://54.243.129.126/usr_content/pics/50ff45e3e6ed8_t.jpg" width="80px;" height="80px;" style="margin-top:3px;"/>
							<img src="http://54.243.129.126/usr_content/pics/50ff461cd9e91_t.jpg" width="80px;" height="80px;" style="margin-top:3px;"/>
							<img src="http://54.243.129.126/usr_content/pics/50ff46368d839_t.jpg" width="80px;" height="80px;" style="margin-top:3px;"/>
							<img src="http://54.243.129.126/usr_content/pics/50ff464d82a39_t.jpg" width="80px;" height="80px;" style="margin-top:3px;"/>
							<img src="http://54.243.129.126/usr_content/pics/50ff467f23097_t.jpg" width="80px;" height="80px;" style="margin-top:3px;"/>
							<img src="http://54.243.129.126/usr_content/pics/50ff469a53f8d_t.jpg" width="80px;" height="80px;" style="margin-top:3px;"/>
							<img src="http://54.243.129.126/usr_content/pics/50ff46c771906_t.jpg" width="80px;" height="80px;" style="margin-top:3px;"/>
							<img src="http://54.243.129.126/usr_content/pics/50ff47d09a6e3_t.jpg" width="80px;" height="80px;" style="margin-top:3px;"/>
							<img src="http://54.243.129.126/usr_content/pics/50ff481210576_t.jpg" width="80px;" height="80px;" style="margin-top:3px;"/>
							<img src="http://54.243.129.126/usr_content/pics/50ff48335d172_t.jpg" width="80px;" height="80px;" style="margin-top:3px;"/>
							<img src="http://54.243.129.126/usr_content/pics/50ff48605236e_t.jpg" width="80px;" height="80px;" style="margin-top:3px;"/>
							<img src="http://54.243.129.126/usr_content/pics/50ff4881be34a_t.jpg" width="80px;" height="80px;" style="margin-top:3px;"/>
							<img src="http://54.243.129.126/usr_content/pics/50ff594a7714d_t.jpg" width="80px;" height="80px;" style="margin-top:3px;"/>
							<img src="http://54.243.129.126/usr_content/pics/50ff5a1ae0091_t.jpg" width="80px;" height="80px;" style="margin-top:3px;"/>
							<img src="http://54.243.129.126/usr_content/pics/50ff5a2f872c1_t.jpg" width="80px;" height="80px;" style="margin-top:3px;"/>
						</div>
						<h3>Links</h3>
						<div class="round-y">
							<a href="" style="color:black;">Father vs Son story</a><br />
							<a href="" style="color:black;">Lakers</a><br />
							<a href="" style="color:black;">Rio Ferdinand debate</a><br />
							<a href="" style="color:black;">AVB praise</a>
						</div>
						<h3>Music</h3>
						<div class="round-y">
							<p>Music is here.<p>
						</div>
						<h3>Memories</h3>
						<div class="round-y">
							<p>Memories area.</p>
						</div>
						<h3>Lyrics</h3>
						<div class="round-y">
							<p>Lyrics section.</p>
						</div>
						<h3>Quotes</h3>
						<div class="round-y">
							<span style='color:black;'>Imagine all the people, living life in peace. <b style='color:black;'>John Lennon</b></span><br />
							<span style='color:black;'>Please to meet you, hope you guess my name. <b style='color:black;'>Rolling Stones</b></span><br />
						</div>
					</div>
				</div>
			</td>
			<td width="70%" style="border-left:2px solid black; padding:10px;" valign="top">
				<div style="overflow:scroll; height:100%;">
				<div class="unite-post">
					<table border="0" width="100%;">
						<tr>
							<td valign="top" style="width:46px;"><img src="http://54.243.129.126/usr_content/pics/50ff5af407f2b_t.jpg" class="img-circle" width="45px" height="45px" /></td>
							<td>
								<table border="0" width="100%">
									<tr>
										<td style="height:43px;"><a href="" style="color:blue; font-size:15px; font-weight:bold;">Harry</a></td>
									</tr>
									<tr>
										<td>
											<table border="0" width="100%">
												<tr>
													<td width="50%"><img src="http://54.243.129.126/usr_content/pics/512061d3cb388_t.jpg" width="250px" /></td>
													<td width="50%"><img src="http://54.243.129.126/usr_content/pics/512061ec972bf_t.jpg" width="250px" /></td>
												</tr>
											</table>
										</td>
									</tr>
									<tr>
										<td align="center">
											<span style="font-size:13px; color:grey;">3 hours ago</span>
											<div class='btn-group'>
												<button onclick='clap(0);' class='btn btn-small user_type btn-inverse btn-clap' rel='tooltip' title='Clap' data-placement='top' data-trigger='hover'><img src='http://i.imm.io/1aktX.png' width='15px' height='15px' style='position:relative; bottom:2px;'/> <span style='color:yellow; font-weight:700;' class='clap'>0</span></button>
												<!--<button onclick='unite();' class='btn btn-small btn-inverse' style='height:26px;'><img src='http://i.imm.io/1aqsI.png' width='13px' height='13px' /></button>-->
												<button onclick='showComment("+parseJSON.data[i].id+");' style='height:26px;' class='btn btn-small user_type btn-inverse btn-respond' rel='tooltip' title='Respond' data-placement='top' data-trigger='hover'><img src='http://i.imm.io/1aktR.png' width='20px' height='20px' style='position:relative; bottom:2px;'/></button>
											</div>
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</div>
				<div class="unite-post">
					<table border="0" width="100%;">
						<tr>
							<td valign="top" style="width:46px;"><img src="http://54.243.129.126/usr_content/pics/50ff5af407f2b_t.jpg" class="img-circle" width="45px" height="45px" /></td>
							<td>
								<table border="0" width="100%">
									<tr>
										<td style="height:43px;"><a href="" style="color:blue; font-size:15px; font-weight:bold;">Harry</a></td>
									</tr>
									<tr>
										<td>
											<table border="0" width="100%">
												<tr>
													<td width="50%"><img src="http://54.243.129.126/usr_content/pics/510020db0121e_t.jpg" width="250px" /></td>
													<td width="50%">
														<div style="color:black;">
															<i><b style="color:black;">Imagine all the people, living life in peace.</b></i><br />
															<i style="color:black;">John Lennon</i>
														</div>
													</td>
												</tr>
											</table>
										</td>
									</tr>
									<tr>
										<td align="center">
											<span style="font-size:13px; color:grey;">3 hours ago</span>
											<div class='btn-group'>
												<button onclick='clap(0);' class='btn btn-small user_type btn-inverse btn-clap' rel='tooltip' title='Clap' data-placement='top' data-trigger='hover'><img src='http://i.imm.io/1aktX.png' width='15px' height='15px' style='position:relative; bottom:2px;'/> <span style='color:yellow; font-weight:700;' class='clap'>0</span></button>
												<!--<button onclick='unite();' class='btn btn-small btn-inverse' style='height:26px;'><img src='http://i.imm.io/1aqsI.png' width='13px' height='13px' /></button>-->
												<button onclick='showComment("+parseJSON.data[i].id+");' style='height:26px;' class='btn btn-small user_type btn-inverse btn-respond' rel='tooltip' title='Respond' data-placement='top' data-trigger='hover'><img src='http://i.imm.io/1aktR.png' width='20px' height='20px' style='position:relative; bottom:2px;'/></button>
											</div>
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</div>
				<div class="unite-post">
					<table border="0" width="100%;">
						<tr>
							<td valign="top" style="width:46px;"><img src="http://54.243.129.126/usr_content/pics/50ff5af407f2b_t.jpg" class="img-circle" width="45px" height="45px" /></td>
							<td>
								<table border="0" width="100%">
									<tr>
										<td style="height:43px;"><a href="" style="color:blue; font-size:15px; font-weight:bold;">Harry</a></td>
									</tr>
									<tr>
										<td>
											<table border="0" width="100%">
												<tr>
													<td width="50%">
														<p style="color:black; font-size:14px;"><b style="color:black;">2008</b><br />After Jonathan Woodage scored an extra time header to beat Chelsea in the league cup final, I can honestly and maybe even sadly say that was probably one of the best feelings of my life. Beating the scum is one thing, but at wembley to win the cup is another having bullied them all game. TTID</p>
													</td>
													<td width="50%">
														<div class="unite-link">
															<a style="color:black; font-size:15px; text-decoration:underline;" href="http://goo.gl/HtPU9">Best day of my life. Spurs 2-1 Chelsea to win the cup.</a>
														</div>
													</td>
												</tr>
											</table>
										</td>
									</tr>
									<tr>
										<td align="center">
											<span style="font-size:13px; color:grey;">3 hours ago</span>
											<div class='btn-group'>
												<button onclick='clap(0);' class='btn btn-small user_type btn-inverse btn-clap' rel='tooltip' title='Clap' data-placement='top' data-trigger='hover'><img src='http://i.imm.io/1aktX.png' width='15px' height='15px' style='position:relative; bottom:2px;'/> <span style='color:yellow; font-weight:700;' class='clap'>0</span></button>
												<!--<button onclick='unite();' class='btn btn-small btn-inverse' style='height:26px;'><img src='http://i.imm.io/1aqsI.png' width='13px' height='13px' /></button>-->
												<button onclick='showComment("+parseJSON.data[i].id+");' style='height:26px;' class='btn btn-small user_type btn-inverse btn-respond' rel='tooltip' title='Respond' data-placement='top' data-trigger='hover'><img src='http://i.imm.io/1aktR.png' width='20px' height='20px' style='position:relative; bottom:2px;'/></button>
											</div>
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</div>
				<div class="unite-post">
					<table border="0" width="100%;">
						<tr>
							<td valign="top" style="width:46px;"><img src="http://54.243.129.126/usr_content/pics/50ff5af407f2b_t.jpg" class="img-circle" width="45px" height="45px" /></td>
							<td>
								<table border="0" width="100%">
									<tr>
										<td style="height:43px;"><a href="" style="color:blue; font-size:15px; font-weight:bold;">Harry</a></td>
									</tr>
									<tr>
										<td>
											<table border="0" width="100%">
												<tr>
													<td width="50%"><img src="http://54.243.129.126/usr_content/pics/50ff46368d839_t.jpg" width="250px" /></td>
													<td width="50%"><img src="http://54.243.129.126/usr_content/pics/5108312679870_t.jpg" width="250px" /></td>
												</tr>
											</table>
										</td>
									</tr>
									<tr>
										<td align="center">
											<span style="font-size:13px; color:grey;">3 hours ago</span>
											<div class='btn-group'>
												<button onclick='clap(0);' class='btn btn-small user_type btn-inverse btn-clap' rel='tooltip' title='Clap' data-placement='top' data-trigger='hover'><img src='http://i.imm.io/1aktX.png' width='15px' height='15px' style='position:relative; bottom:2px;'/> <span style='color:yellow; font-weight:700;' class='clap'>0</span></button>
												<!--<button onclick='unite();' class='btn btn-small btn-inverse' style='height:26px;'><img src='http://i.imm.io/1aqsI.png' width='13px' height='13px' /></button>-->
												<button onclick='showComment("+parseJSON.data[i].id+");' style='height:26px;' class='btn btn-small user_type btn-inverse btn-respond' rel='tooltip' title='Respond' data-placement='top' data-trigger='hover'><img src='http://i.imm.io/1aktR.png' width='20px' height='20px' style='position:relative; bottom:2px;'/></button>
											</div>
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</div>
				</div>
			</td>
		</tr>
	</table>
</div>